### ISSUE TITLE
Validate method on a map instance does not evaluate stored computes

### ISSUE THREAD

**Issue by Macrofig** [canjs/can-validate#27]
If a property has validate options with functions (which are converted to computes), they will not be evaluated when the map instance's `validate` method is called.  Instead of being evaluated, the function is passed to validateJs which will return errors because `this` is null (`this` in the function refers to the map instance).

Make the validate method evaluate the computes before calling the shim's `validate` method.

**Comment by mindfulmike** [comment]
![screen shot 2016-05-27 at 1 00 38 pm](https://cloud.githubusercontent.com/assets/11395060/15615330/aac2fbf2-240b-11e6-8799-ff512929a234.png)
This looks to happen when the required compute is executed when setting another value in the same map.

**Comment by Macrofig** [comment]
Fixed in PR #29

**Comment by Macrofig** [comment]
Thanks for the test case, btw @mindfulmike. I used your situation to help verify my fix!
