### ISSUE TITLE
can-validate for 3.0

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-validate#42]
# Tasks 

- create formatErrors utility method
- documenting the `validator` type def
- document the `error` type def

# Proposal

## Goals

 - to create a core set of validation utilities that can power validations on DefineMaps and computes.
 - to make it easy to integrate other validation library behavior
 - to support validations on single stateful values, and collections of independent stateful values.

## Terminology

_single stateful value_ - This can be something like a string, number, or date instance.  It's something that has only a single value representation.

_collections_ - This has multiple stateful values or `parts`

_reason_ - A reason for being invalid.

## Postulations

- A single stateful value 
    - Can be invalid for one or more reasons or be valid 

- A collection of independent stateful values 
    - The collection can be invalid for one or more reasons or be valid 
    - A reason can be related to one or many `parts` of a collection.
    - A reason for being invalid on individual values can be used as a reasons for 
      the whole.

## Proposal 

I'm proposing the following core `TYPEDEF`s:

### ERROR typedef

`{message: STRING, related: Array<String>}`

A representation of a reason a validation went wrong.

 - __message__ - A reason why some value is in an invalid state. (Alt: `reason`)
 - __related__ - _optional_ - An array of related `parts` for this error.

### VALIDATOR typedef

`validator(value) -> null | undefined | String | ERROR | [ String | Error ]`

A function that returns the reasons for being invalid or `null` or `undefined` if `value` is not invalid.

 - __value__ - A single stateful value or a collection. 

Returns:
 - `null` or `undefined` - if the value is valid.
 - `String` - A reason the object is invalid.
 - `ERROR` - A reason the object is invalid with associated parts.
 - `[String | ERROR]` - Reasons why the object is invalid.

### `validate.formatErrors( [inputFormatName], outputFormatName, errors )`

A helper function that can take the `ERROR` format or other formats and convert to each 
other.  Formats to start should probably be just:

 - "object" - for `{propName: [reason1, reason2]}` format
 - "flat" - for `[reason1, reason2]` format
 - "errors" - for `[{error: "STRING", related: []}]` format

**Comment by justinbmeyer** [comment]
As a decorator in ES5:

```
var validate = require("can-define-validate-validatejs");
var Locator = DefineMap.extend({ ... })
validate()(Locator);
```

**Comment by BigAB** [comment]
Might be nice to use ES.next decorators on a per attribute basis

```
export const ViewModel = DefineMap.extend({
  @validate({
    required: true,
    pattern: /\w\w/
  })
  state: 'string',
  
  @validate({
    required: true,
    numericality: true
  })
  zipCode: 'string'
})
```

...or if the define map is okay with arbitrary properties in the definition objects:
```
export const ViewModel = DefineMap.extend({
  @validate
  state: {
    type: 'string',
    required: true,
    pattern: /\w\w/
  }
  
  @validate
  zipCode: {
    type: 'string'
    required: true,
    numericality: true
  }
})
```
