### ISSUE TITLE
can-validate API

### ISSUE THREAD

**Issue by Macrofig** [canjs/can-validate#44]
`can-validate` for CanJS 3.0 should manage validations and validation libraries then expose methods to the validations. It should also manage errors for a particular value (or set of values, i.e. an object or map).

For this first stage, we are just concerned with validating simple values.

## `registerValidation` Register a validation callback. 

Given a callback like the following that checks if a value is required...

```javascript
var requiredValidator = function (val, isRequired) {
  if (typeof val === 'undefined' && isRequired) {
    return 'is required.';
  }
};
```

we should be able to register this "validation" with `can-validate` like so

```javascript
validate.registerValidator('required', requiredValidator);
```

Now I can check if a value is valid based on the `required` constraint.

## `test` Test a value against constraints

Assuming validations have been registered, we can now test a value using `test`.

Given the following values and constraints...

```javascript
var firstName = 'juan';
var lastName = '';

var constraints = {
  required: true
};
```

We can test a value by doing

```javascript
validate.test(firstName, constraints); //> true
validate.test(lastName, constraints); //> false
```

## `errors` Get any errors set by the test method

Assuming validations have been registered, we can use `errors` to retrieve any errors set by `test`.

Given the following values and constraints...

```javascript
var firstName = '';

var constraints = {
  required: true
};
```

And we tested the value like this...
```javascript
validate.test(firstName, constraints); //> false
```

We can get the errors by running...

```javascript
validate.errors();//> ['is required.']
```

**Comment by Macrofig** [comment]
The `test` method will work something like this:

- call test `validate.test()`
- if validations are set
- loop through constraints
- if validation callback exists
- run validation callback
- parse response (should match `error` typedef), result should be an object
- push parsed response in an error array
- when no more constraints
- set error array to property on validate instance
- if error array is greater than 0, return false, else return true

**Comment by justinbmeyer** [comment]
My proposal:

```js
var makeValidate = require("can-validate-validatejs");

validateAge = makeValidate({
    presence: true
});

var validatePerson = canValidate.many({
    age: {
        presence: true
    },
    name: {
        
    }
});

$("form").on("submit", function(){
    var $el = $(this);

    var age = $el.find("input[name=age]").val();

    var errors = validateAge(age);

    if(errors) {
        $(".errors").html( canValidate.formatErrors(errors, "flat").join(", ") )
    }

    var errors = validatePerson( {
        name: "Juan",
        age: 35
    });
})
```
